name: lastfm
description: Develop a music search app using last.fm’s API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  dio: ^4.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  url_launcher: ^6.0.12

dev_dependencies:
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true